enum PubSubEvent {
  API_URL_CHANGED = 'API_URL_CHANGED',
  PHONE_NUMBER_CHANGED = 'PHONE_NUMBER_CHANGED',
  THEME_TOGGLED = 'THEME_TOGGLED',
  MESSAGE_RECEIVED = 'MESSAGE_RECEIVED',
  NOTIFICATION_RECEIVED = 'NOTIFICATION_RECEIVED',
  NOTIFICATION_TAPPED = 'NOTIFICATION_TAPPED',
}

export default PubSubEvent;
